solution/config/routes.rb
NewsReader::Application.routes.draw do
  resource :session
  resources :users
  namespace :api do
    resources :feeds, only: [:index, :create, :show] do
      resources :entries, only: [:index]
    end
    resources :entries, only: [:show]
  end

  root to: "static_pages#index"
end

solution/app/models/entry.rb
class Entry < ActiveRecord::Base

  belongs_to :feed

  def self.create_from_json!(entryData, feed)
    Entry.create!({
      guid: entryData.guid,
      link: entryData.link,
      published_at: entryData.pubDate,
      title: entryData.title,
      json: entryData.to_json,
      feed_id: feed.id
    })
  end
end

solution/app/models/feed.rb
require 'open-uri'

class Feed < ActiveRecord::Base
  has_many :entries, :dependent => :destroy
  has_many :user_feeds
  has_many :users, :through => :user_feeds

  def has_favorited?(user_id)
    !users.find_by_id(user_id).nil?
  end

  def self.find_or_create_by_url(url)
    feed = Feed.find_by_url(url)
    return feed if feed

    begin
      feed_data = SimpleRSS.parse(open(url))
      feed = Feed.create!(title: feed_data.title, url: url)
      feed_data.entries.each do |entry_data|
        Entry.create_from_json!(entry_data, feed)
      end
    rescue SimpleRSSError
      return nil
    end

    feed
  end

  def latest_entries
    reload if updated_at < 30.seconds.ago
    entries
  end

  def reload
    # reloads entries
    begin
      feed_data = SimpleRSS.parse(open(url))
      self.title = feed_data.title
      save!

      existing_entry_guids = Entry.pluck(:guid).sort
      feed_data.entries.each do |entry_data|
        unless existing_entry_guids.include?(entry_data.guid)
          Entry.create_from_json!(entry_data, self)
        end
      end

      self
    rescue SimpleRSSError
      return false
    end
  end
end

solution/app/models/user.rb
require 'bcrypt'
class User < ActiveRecord::Base
  has_many :user_feeds

  def password=(pass)
    self.password_digest = BCrypt::Password.create(pass)
  end

  def is_password?(pass)
    BCrypt::Password.new(self.password_digest).is_password?(pass)
  end

  def self.find_by_credentials(params)
    u = User.find_by_username(params[:username])
    return u if u && u.is_password?(params[:password])
    nil
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end
end

solution/app/models/user_feed.rb
class UserFeed < ActiveRecord::Base

  belongs_to :feed
  belongs_to :user
end

solution/app/controllers/api/entries_controller.rb
class Api::EntriesController < ApplicationController
  def index
    feed = Feed.find(params[:feed_id])
    render :json => feed.latest_entries
  end
  def show
    render :json => Entry.find(params[:id]);
  end
end

solution/app/controllers/api/feeds_controller.rb
class Api::FeedsController < ApplicationController
  def index
    render :json => Feed.all
  end

  def show
    render :json => Feed.find(params[:id]), :include => :latest_entries
  end

  def create
    feed = Feed.find_or_create_by_url(feed_params[:url])
    if feed
      render :json => feed
    else
      render :json => { error: "invalid url" }, status: :unprocessable_entity
    end
  end

  private

  def feed_params
    params.require(:feed).permit(:title, :url)
  end
end

solution/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

solution/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    u = User.find_by_credentials(params[:user])
    if u
      login!(u)
      redirect_to "/"
    else
      redirect_to new_session_url
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end
end

solution/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index

  end
end

solution/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to "/"
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:password, :session_token, :username)
  end
end

solution/app/helpers/application_helper.rb
module ApplicationHelper
end

solution/app/helpers/entries_helper.rb
module EntriesHelper
end

solution/app/helpers/feeds_helper.rb
module FeedsHelper
end

solution/app/helpers/sessions_helper.rb
module SessionsHelper
  def login!(user)
    session[:token] = user.reset_session_token!
  end

  def logout!
    current_user.reset_session_token!
  end

  def current_user
    @current_user ||= User.find_by_session_token(session[:token])
  end

  def logged_in?
    !!current_user
  end

  def require_user!
    redirect_to new_session_url unless logged_in?
  end
end

solution/app/helpers/users_helper.rb
module UsersHelper
end

solution/app/views/feeds/index.html.erb
<h1 class="main-title">
  <a href="#">New.read.er</a>
  <%= button_to "Sign Out", session_url, :method => :delete, :class => "add-button" %>
</h1>

<div id='sidebar'></div>

<div id='content'>
  <a href="/users/new">Sign Up</a>
  <a href="/session/new">Log In</a>
</div>

solution/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewsReader</title>
    <link href='http://fonts.googleapis.com/css?family=News+Cycle:400,700' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

solution/app/views/static_pages/index.html.erb
<h1 class="main-title">
  <a href="#">New.read.er</a>
  <%= button_to "Sign Out", session_url, :method => :delete, :class => "add-button" %>
</h1>

<div id='sidebar'></div>

<div id='content'>
  <a href="/users/new">Sign Up</a>
  <a href="/session/new">Log In</a>
</div>

solution/app/views/users/new.html.erb
<form action="/users" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for="username">Username</label><br>
  <input id="username" name="user[username]" type="text"><br>
  <label for="password">Password</label><br>
  <input id="password" name="user[password]" type="password"><br>
  <input type="submit" value="Submit"><br>
</form>m